openapi: 3.0.3
info:
  version: v1
  title: FarmStall API
servers:
- url: https://farmstall.designapis.com/v1
paths:
  /reviews:
    # get: ...
    post:
      description: Create a new Review
      requestBody:
        description: A new Review
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                rating:
                  type: integer
                  minimum: 1
                  maximum: 5
                userId:
                  type: string
                  pattern: '^[0-9a-fA-F\-]{36}$'
                  nullable: true
      responses:
        '201':
          description: Successfully created a new Review
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: An awesome time for the whole family.
                  rating:
                    type: integer
                    minimum: 1
                    maximum: 5
                  userId:
                    type: string
                    nullable: true
                    pattern: '^[0-9a-fA-F\-]{36}$'
                  uuid:
                    type: string
                    pattern: '^[0-9a-fA-F\-]{36}$'
  /reviews/{reviewId}:
    get:
      description: Get a single review
      parameters:
      - name: reviewId
        in: path
        required: true
        schema:
          type: string
          description: The review's ID
          example: 3b5b1707-b82c-4b1d-9078-157053902525
          minLength: 36
          maxLength: 36
          pattern: '[a-zA-Z0-9-]+'
      responses:
        '200':
          description: A single review
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  rating:
                    type: integer
                    minimum: 1
                    maximum: 5
                  userId:
                    minLength: 36
                    maxLength: 36
                    pattern: '^[a-zA-Z0-9-]+$'
                    nullable: true
                  uuid:
                    minLength: 36
                    maxLength: 36
                    pattern: '^[a-zA-Z0-9-]+$'
