[package]
name = "rusty"
version = "0.1.0"
authors = ["alecordev"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "embed"
crate-type = ["dylib"]